#!/bin/sh

capture_region() {
  grim -c -g "$(slurp -o -c '#ff0000ff')" -t ppm - | satty -f -
}

capture_fullscreen() {
  grim -t ppm - | satty -f -
}

if [ "$1" = "fullscreen" ]; then
  capture_fullscreen
else
  capture_region
fi
